import type {
  CommunityCommentProjectionRow,
  CommunityDatabaseBindingRow,
  CommunityFollowProjectionRow,
  CommunityMembershipProjectionRow,
  CommunityPostProjectionRow,
  CommunityRow,
  JobRow,
} from "../auth/auth-db-rows"
import type { Post } from "../../types"

export interface CommunityRepositoryLifecycle {
  close?(): void | Promise<void>
}

export interface CommunityReadRepository {
  getCommunityById(communityId: string): Promise<CommunityRow | null>
  getCommunityByRouteSlug(routeSlug: string): Promise<CommunityRow | null>
  getCommunityByNamespaceVerificationId(namespaceVerificationId: string): Promise<CommunityRow | null>
  listActiveCommunities(input?: {
    limit?: number
  }): Promise<CommunityRow[]>
  searchActiveCommunities(input: {
    query: string
    limit: number
  }): Promise<CommunityRow[]>
}

export interface CommunityDatabaseBindingRepository {
  getPrimaryCommunityDatabaseBinding(communityId: string): Promise<CommunityDatabaseBindingRow | null>
}

export interface CommunityJobReadRepository {
  getJobById(jobId: string): Promise<JobRow | null>
  getLatestCommunityProvisioningJob(communityId: string): Promise<JobRow | null>
}

export type CommunityProvisioningMode = "local_dev" | "d1_native"

export type InitialCommunityDatabaseBinding = {
  organizationSlug: string
  groupName: string
  groupId: string | null
  databaseName: string
  databaseId: string | null
  databaseUrl: string
  location: string | null
  requiresCredentials: boolean
  provisioningMode: CommunityProvisioningMode
}

export interface CommunityPostProjectionRepository {
  getCommunityPostProjectionByPostId(postId: string): Promise<CommunityPostProjectionRow | null>
  recordCommunityPostProjection(input: {
    communityId: string
    sourcePostId: string
    authorUserId: string | null
    identityMode: "public" | "anonymous"
    postType: "text" | "image" | "video" | "link" | "song" | "crosspost"
    status: Post["status"]
    visibility: "public" | "members_only"
    sourceCreatedAt: string
    projectedPayloadJson: string
    actorUserId: string
    createdAt: string
  }): Promise<CommunityPostProjectionRow>
  updateCommunityPostProjectionStatus(input: {
    postId: string
    status: CommunityPostProjectionRow["status"]
    updatedAt: string
  }): Promise<void>
  updateCommunityPostProjectionPayload(input: {
    postId: string
    projectedPayloadJson: string
    updatedAt: string
  }): Promise<void>
  updateCommunityPostProjectionMetrics(input: {
    postId: string
    upvoteCount: number
    downvoteCount: number
    commentCount: number
    likeCount: number
    updatedAt: string
  }): Promise<void>
}

export interface CommunityCommentProjectionRepository {
  getCommunityCommentProjectionByCommentId(commentId: string): Promise<CommunityCommentProjectionRow | null>
  recordCommunityCommentProjection(input: {
    communityId: string
    threadRootPostId: string
    sourceCommentId: string
    parentCommentId: string | null
    depth: number
    status: "published" | "hidden" | "removed" | "deleted"
    sourceCreatedAt: string
    actorUserId: string
    createdAt: string
  }): Promise<CommunityCommentProjectionRow>
}

export interface CommunityMembershipProjectionRepository {
  listCommunityMembershipProjectionsByUserId(userId: string): Promise<CommunityMembershipProjectionRow[]>
  listCommunityFollowProjectionsByUserId(userId: string): Promise<CommunityFollowProjectionRow[]>
  upsertCommunityMembershipProjection(input: {
    communityId: string
    userId: string
    membershipState: CommunityMembershipProjectionRow["membership_state"]
    sourceUpdatedAt: string
    createdAt: string
  }): Promise<void>
  upsertCommunityFollowProjection(input: {
    communityId: string
    userId: string
    followState: CommunityFollowProjectionRow["follow_state"]
    sourceUpdatedAt: string
    unfollowedAt: string | null
    createdAt: string
  }): Promise<void>
  incrementCommunityFollowerCount(input: {
    communityId: string
    delta: 1 | -1
    updatedAt: string
  }): Promise<void>
  setCommunityFollowerCount(input: {
    communityId: string
    followerCount: number
    updatedAt: string
  }): Promise<void>
}

export interface CommunityProvisioningRepository {
  /**
   * Look up the primary binding row for a community. Used by the d1_native
   * orchestrator (step 4) to find the binding ID generated by
   * createCommunityProvisioningRequest, so it can UPDATE the row with the
   * resolved d1:// URL.
   */
  getPrimaryCommunityDatabaseBinding(communityId: string): Promise<CommunityDatabaseBindingRow | null>
  createCommunityProvisioningRequest(input: {
    communityId: string
    communityDatabaseBindingId: string
    jobId: string
    creatorUserId: string
    displayName: string
    description?: string | null
    avatarRef?: string | null
    bannerRef?: string | null
    membershipMode: "open" | "request" | "gated"
    namespaceVerificationId: string | null
    routeSlug?: string | null
    binding: InitialCommunityDatabaseBinding
    createdAt: string
  }): Promise<{
    community: CommunityRow
    binding: CommunityDatabaseBindingRow
    job: JobRow
  }>
  retryCommunityProvisioningRequest(input: {
    communityId: string
    fallbackBindingId: string
    jobId: string
    namespaceVerificationId: string
    routeSlug: string
    binding: InitialCommunityDatabaseBinding
    createdAt: string
  }): Promise<{
    community: CommunityRow
    binding: CommunityDatabaseBindingRow
    job: JobRow
  }>
  markCommunityProvisioningSucceeded(input: {
    communityId: string
    communityDatabaseBindingId: string
    jobId: string
    actorUserId: string
    resultRef: string | null
    description?: string | null
    avatarRef?: string | null
    bannerRef?: string | null
    createdAt: string
    metadata: Record<string, unknown>
  }): Promise<{
    community: CommunityRow
    job: JobRow
  }>
  markCommunityProvisioningFailed(input: {
    communityId: string
    jobId: string
    actorUserId: string
    errorCode: string
    createdAt: string
    metadata: Record<string, unknown>
  }): Promise<void>
  /**
   * Seed (or advance) a `backend='d1'` row in `community_database_routing`.
   * Called by the d1_native provisioning orchestrator (step 4 of the D1-native
   * workstream) to flip the row from 'provisioning' to 'ready' after the
   * snapshot load succeeds. Mirrors `upsertD1CommunityRoutingRow` in
   * community-routing-repository.ts.
   */
  upsertD1CommunityRoutingRow(input: {
    communityId: string
    shardWorkerId: string
    bindingName: string
    region: string
    now: string
    provisioningState?: "provisioning" | "ready" | "degraded" | "decommissioned"
  }): Promise<{ written: boolean }>
  /**
   * Finalize a d1-native community's binding row after the allocator has
   * produced a concrete bindingName. Replaces the `d1://pending-…invalid`
   * sentinel URL written at create time with the resolved `d1://shard/<binding>`
   * URL and clears `requires_credentials`. Mirrors `persistProvisionedD1Binding`
   * in provisioning/repository.ts.
   */
  persistProvisionedD1Binding(input: {
    communityDatabaseBindingId: string
    bindingName: string
    databaseUrl: string
    region: string
    updatedAt: string
  }): Promise<void>
}

export interface CommunityMutationRepository {
  updateCommunitySeoProjection(input: {
    communityId: string
    description: string | null
    avatarRef: string | null
    bannerRef: string | null
    updatedAt: string
  }): Promise<void>
  attachNamespaceToCommunity(input: {
    communityId: string
    namespaceVerificationId: string
    routeSlug: string
    updatedAt: string
  }): Promise<CommunityRow>
  setPendingNamespaceVerificationSession(input: {
    communityId: string
    sessionId: string | null
    updatedAt: string
  }): Promise<void>
  setCommunityLifecycleStatus(input: {
    communityId: string
    targetStatus: CommunityRow["status"]
    allowedFromStatuses: readonly CommunityRow["status"][]
    updatedAt: string
  }): Promise<CommunityRow>
}

export interface CommunityRepository
  extends CommunityRepositoryLifecycle,
    CommunityReadRepository,
    CommunityDatabaseBindingRepository,
    CommunityJobReadRepository,
    CommunityPostProjectionRepository,
    CommunityCommentProjectionRepository,
    CommunityMembershipProjectionRepository,
    CommunityProvisioningRepository,
    CommunityMutationRepository {
  // Settlement-capable routes only (ready, non-decommissioned D1). Used by the unattended
  // booking-settlement cron so it enumerates from authoritative routing state, never the
  // generic active-community list. Lives on the full repository (not the narrow read interface)
  // so unrelated read-only mocks are not forced to implement it.
  listSettlementEligibleCommunities(input?: {
    limit?: number
  }): Promise<Array<{ community_id: string; created_at: string }>>
}
