/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 897eb7de819396cb5b50fdde59f92667)
interface __BaseEnv_Env {
	ENVIRONMENT: "staging" | "development";
	UPSTREAM_RPC_URL: "https://aeneid.storyrpc.io";
	DRILLS: DurableObjectNamespace<import("./src/index").ControlledInclusionDrill>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "ControlledInclusionDrill";
	}
	interface StagingEnv {
		ENVIRONMENT: "staging";
		UPSTREAM_RPC_URL: "https://aeneid.storyrpc.io";
		DRILLS: DurableObjectNamespace<import("./src/index").ControlledInclusionDrill>;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT" | "UPSTREAM_RPC_URL">> {}
}
