import { readdirSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { createHash } from "node:crypto";

const CORE_REPO_ROOT = process.env.PIRATE_CORE_REPO
  ? resolve(process.env.PIRATE_CORE_REPO)
  : resolve(import.meta.dir, "../../../../core");
const MIGRATIONS_DIR = resolve(
  CORE_REPO_ROOT,
  "db/community-template/migrations",
);
const OUTPUT_FILE = resolve(
  import.meta.dir,
  "../src/generated/community-migrations.ts",
);

interface MigrationEntry {
  name: string;
  sql: string;
  checksum: string;
}

function checksumSql(sql: string): string {
  return createHash("sha256").update(sql).digest("hex");
}

function generateMigrationManifest(): void {
  const entries = readdirSync(MIGRATIONS_DIR)
    .filter((name) => name.endsWith(".sql"))
    .sort();

  const migrations: MigrationEntry[] = entries.map((name) => {
    const sql = readFileSync(resolve(MIGRATIONS_DIR, name), "utf8");
    return {
      name,
      sql,
      checksum: checksumSql(sql),
    };
  });

  mkdirSync(dirname(OUTPUT_FILE), { recursive: true });

  const lines: string[] = [
    "// Auto-generated by scripts/generate-migration-manifest.ts",
    "// Do not edit manually. Regenerate with: bun run scripts/generate-migration-manifest.ts",
    "",
    "export type CommunityMigrationEntry = {",
    "  readonly name: string;",
    "  readonly sql: string;",
    "  readonly checksum: string;",
    "};",
    "",
    "export const COMMUNITY_MIGRATIONS: readonly CommunityMigrationEntry[] = [",
  ];

  for (const migration of migrations) {
    const escapedSql = migration.sql
      .replace(/\\/g, "\\\\")
      .replace(/`/g, "\\`")
      .replace(/\$/g, "\\$");
    lines.push("  {");
    lines.push(`    name: ${JSON.stringify(migration.name)},`);
    lines.push(`    sql: \`${escapedSql}\`,`);
    lines.push(`    checksum: ${JSON.stringify(migration.checksum)},`);
    lines.push("  },");
  }

  lines.push("] as const;");
  lines.push("");

  writeFileSync(OUTPUT_FILE, lines.join("\n"), "utf8");

  console.log(
    `generated ${migrations.length} migrations to ${OUTPUT_FILE}`,
  );
}

generateMigrationManifest();
