import { describe, expect, test } from "bun:test"
import {
  isD1NativeProvisioningSelected,
  resolveCommunityProvisioningBackend,
} from "./backend"
import type { Env } from "../../../env"
import type { ShardRpc } from "@pirate/api-shared"
import type { CommunityProvisioningRepository } from "../community-repository-types"

// A truthy stand-in for the shard RPC binding; the resolver only checks presence.
const fakeShard = {} as unknown as ShardRpc

function buildEnv(overrides: Partial<Env> = {}): Env {
  return { ENVIRONMENT: "production", ...overrides } as Env
}

describe("resolveCommunityProvisioningBackend", () => {
  test("selects d1_native for a namespaceless request when the flag is set AND the shard binding exists", () => {
    const env = buildEnv({ COMMUNITY_PROVISION_BACKEND: "d1_native", COMMUNITY_D1_SHARD: fakeShard })
    expect(isD1NativeProvisioningSelected(env)).toBe(true)
    expect(resolveCommunityProvisioningBackend(env, { hasNamespace: false }).mode).toBe("d1_native")
  })

  test("routes a namespaced request to turso_operator even when the d1_native flag is set (v1 scope)", () => {
    // v1 of d1_native is namespaceless-only. Flipping the env flag must NOT
    // brick namespaced community creation — namespaced requests continue to
    // use the Turso operator path regardless of the d1_native flag, because
    // the namespace-attach path can't be routed to d1 today (the
    // upsertLocalNamespaceAttachment call site hits openCommunityDb which
    // fails on d1:// URLs).
    const env = buildEnv({ COMMUNITY_PROVISION_BACKEND: "d1_native", COMMUNITY_D1_SHARD: fakeShard })
    expect(resolveCommunityProvisioningBackend(env, { hasNamespace: true }).mode).toBe("turso_operator")
  })

  test("does NOT select d1_native when the flag is set but the shard binding is absent", () => {
    const env = buildEnv({ COMMUNITY_PROVISION_BACKEND: "d1_native" })
    expect(isD1NativeProvisioningSelected(env)).toBe(false)
    // Falls through to the operator path in a non-dev environment.
    expect(resolveCommunityProvisioningBackend(env, { hasNamespace: false }).mode).toBe("turso_operator")
  })

  test("ignores an unrelated COMMUNITY_PROVISION_BACKEND value (backwards compatible)", () => {
    const env = buildEnv({ COMMUNITY_PROVISION_BACKEND: "turso_operator", COMMUNITY_D1_SHARD: fakeShard })
    expect(isD1NativeProvisioningSelected(env)).toBe(false)
    expect(resolveCommunityProvisioningBackend(env, { hasNamespace: false }).mode).toBe("turso_operator")
  })

  test("default (no flag) keeps local_dev in a dev/test environment", () => {
    const env = buildEnv({ ENVIRONMENT: "test" })
    expect(resolveCommunityProvisioningBackend(env, { hasNamespace: false }).mode).toBe("local_dev")
  })
})

describe("d1NativeProvisioningBackend", () => {
  const env = buildEnv({
    COMMUNITY_PROVISION_BACKEND: "d1_native",
    COMMUNITY_D1_SHARD: fakeShard,
    COMMUNITY_D1_SHARD_REGION: "weur",
  })
  const backend = resolveCommunityProvisioningBackend(env, { hasNamespace: false })

  test("initialBinding produces a credential-free pending d1:// binding", () => {
    const binding = backend.initialBinding({ env, communityId: "cmt_d1", databaseRegion: null })
    expect(binding.provisioningMode).toBe("d1_native")
    expect(binding.databaseUrl).toBe("d1://pending-cmt_d1.invalid")
    expect(binding.requiresCredentials).toBe(false)
    expect(binding.organizationSlug).toBe("shard")
    expect(binding.location).toBe("weur")
  })

  test("initialBinding fails loud when no region is configured", () => {
    const noRegion = buildEnv({ COMMUNITY_PROVISION_BACKEND: "d1_native", COMMUNITY_D1_SHARD: fakeShard })
    expect(() =>
      resolveCommunityProvisioningBackend(noRegion, { hasNamespace: false }).initialBinding({
        env: noRegion,
        communityId: "cmt_d1",
        databaseRegion: null,
      }),
    ).toThrow(/COMMUNITY_D1_SHARD_REGION/)
  })

  test("§8.1 — provision() calls communityD1Bind, then communityD1LoadSnapshot, then upsertD1CommunityRoutingRow('ready'), then persistProvisionedD1Binding", async () => {
    // §8.1 acceptance criterion: the d1_native orchestrator runs to
    // completion against a fake COMMUNITY_D1_SHARD and produces the
    // expected end state (routing row at 'ready', binding URL resolved).
    // The fake shard is observable; we assert on the call sequence.
    const calls: Array<{ m: string; input: unknown }> = []
    const env = buildEnv({
      COMMUNITY_PROVISION_BACKEND: "d1_native",
      COMMUNITY_D1_SHARD: {} as ShardRpc,
      COMMUNITY_D1_SHARD_REGION: "weur",
    })
    const communityId = "cmt_d1_provision_test"
    const bindingId = "cdb_d1_provision_test"
    const repo: CommunityProvisioningRepository = {
      // Step 4 of the orchestrator calls getPrimaryCommunityDatabaseBinding
      // to find the binding ID generated by createCommunityProvisioningRequest.
      async getPrimaryCommunityDatabaseBinding() {
        return {
          community_database_binding_id: bindingId,
          community_id: communityId,
          binding_role: "primary",
          organization_slug: "shard",
          group_name: "shard",
          group_id: null,
          database_name: "pending",
          database_id: null,
          database_url: "d1://pending-cmt_d1_provision_test.invalid",
          location: "weur",
          requires_credentials: false,
          status: "active",
          transferred_at: null,
          created_at: "t0",
          updated_at: "t0",
        }
      },
      async upsertD1CommunityRoutingRow(input) {
        calls.push({ m: "upsertD1CommunityRoutingRow", input })
        return { written: true }
      },
      async persistProvisionedD1Binding(input) {
        calls.push({ m: "persistProvisionedD1Binding", input })
        return undefined
      },
      // Unused in this test — the orchestrator (step 4) doesn't call these.
      async createCommunityProvisioningRequest() {
        throw new Error("unused in this test")
      },
      async retryCommunityProvisioningRequest() {
        throw new Error("unused in this test")
      },
      async markCommunityProvisioningSucceeded() {
        throw new Error("unused in this test")
      },
      async persistProvisionedCommunityDatabaseAccess() {
        throw new Error("unused in this test")
      },
      async markCommunityProvisioningFailed() {
        throw new Error("unused in this test")
      },
    }

    const fakeShard: ShardRpc = {
      async communityD1Bind(input: { communityId: string; now: string }) {
        calls.push({ m: "communityD1Bind", input })
        return {
          ok: true,
          value: { bindingName: "DB_CMTY_D1_TEST", shardWorkerId: "community-d1-shard-staging", allocated: true },
        }
      },
      async communityD1LoadSnapshot(input: { communityId: string; bindingName: string; statements: unknown[] }) {
        calls.push({ m: "communityD1LoadSnapshot", input })
        return { ok: true, value: { rowsAffected: 0, loaded: true } }
      },
    } as unknown as ShardRpc
    const envWithShard = { ...env, COMMUNITY_D1_SHARD: fakeShard }
    const backend = resolveCommunityProvisioningBackend(envWithShard, { hasNamespace: false })

    const r = await backend.provision({
      env: envWithShard,
      communityRepository: repo,
      body: { display_name: "D1 Test", membership_mode: "gated" } as never,
      auth: { userId: "usr_test", communityDisplayName: "D1 Test", createdAt: "t0" } as never,
      communityId,
      namespaceVerificationId: null,
      routeSlug: null,
    })

    // Call sequence: bind → load → upsertRouting('ready') → persistBinding.
    expect(calls.map((c) => c.m)).toEqual([
      "communityD1Bind",
      "communityD1LoadSnapshot",
      "upsertD1CommunityRoutingRow",
      "persistProvisionedD1Binding",
    ])

    // The bind call passed the communityId + now.
    const bind = calls[0]!.input as { communityId: string; now: string }
    expect(bind.communityId).toBe(communityId)
    expect(typeof bind.now).toBe("string")

    // The load call passed the binding name (from bind) + the §8.7 statements
    // (the load array; CONTENT is asserted in d1-snapshot-statements.test.ts —
    // here we pin the orchestrator's call SEQUENCE, robust to mock.module of
    // create/repository in the shared test process).
    const load = calls[1]!.input as { communityId: string; bindingName: string; statements: unknown[] }
    expect(load.communityId).toBe(communityId)
    expect(load.bindingName).toBe("DB_CMTY_D1_TEST")
    expect(Array.isArray(load.statements)).toBe(true)

    // The routing row was upserted at 'ready' with the shard's worker id.
    const upsert = calls[2]!.input as {
      communityId: string
      shardWorkerId: string
      bindingName: string
      region: string
      provisioningState: string
    }
    expect(upsert.communityId).toBe(communityId)
    expect(upsert.shardWorkerId).toBe("community-d1-shard-staging")
    expect(upsert.bindingName).toBe("DB_CMTY_D1_TEST")
    expect(upsert.region).toBe("weur")
    expect(upsert.provisioningState).toBe("ready")

    // The binding row was persisted with the resolved d1:// URL.
    const persist = calls[3]!.input as {
      communityDatabaseBindingId: string
      bindingName: string
      databaseUrl: string
      region: string
    }
    expect(persist.communityDatabaseBindingId).toBe(bindingId)
    expect(persist.bindingName).toBe("DB_CMTY_D1_TEST")
    expect(persist.databaseUrl).toBe("d1://shard/DB_CMTY_D1_TEST")
    expect(persist.region).toBe("weur")

    // Returned binding has the resolved d1:// URL.
    expect(r).toMatchObject({
      mode: "d1_native",
      binding: {
        databaseName: "DB_CMTY_D1_TEST",
        databaseUrl: "d1://shard/DB_CMTY_D1_TEST",
        location: "weur",
        requiresCredentials: false,
        provisioningMode: "d1_native",
      },
      credential: null,
    })
  })

  test("provision returns 503 d1_pool_exhausted when the shard pool is empty", async () => {
    // §4.1 acceptance: a shard_pool_exhausted is a transient 503, NOT a
    // generic 500. The orchestrator branches on the raw ShardResult and
    // throws an HttpError with the right status + retryable.
    const env = buildEnv({ COMMUNITY_PROVISION_BACKEND: "d1_native", COMMUNITY_D1_SHARD_REGION: "weur" })
    const fakeShard: ShardRpc = {
      async communityD1Bind() {
        return { ok: false, code: "shard_pool_exhausted", message: "no free bindings" }
      },
    } as unknown as ShardRpc
    const envWithShard = { ...env, COMMUNITY_D1_SHARD: fakeShard }
    const backend = resolveCommunityProvisioningBackend(envWithShard, { hasNamespace: false })
    const repo = {} as CommunityProvisioningRepository
    await expect(
      backend.provision({
        env: envWithShard,
        communityRepository: repo,
        body: {} as never,
        auth: {} as never,
        communityId: "cmt_pool_empty",
        namespaceVerificationId: null,
        routeSlug: null,
      }),
    ).rejects.toMatchObject({
      code: "d1_pool_exhausted",
      status: 503,
      retryable: true,
    })
  })
})
