/**
 * Build-time generator for the D1-native schema-load path (workstream §8.7,
 * option 2 — final-schema-dump).
 *
 * Replays the core/db/community-template migrations into a throwaway in-memory
 * libsql DB, then dumps the FINAL-form schema as CREATE TABLE / CREATE INDEX
 * statements (no ALTER/DROP/PRAGMA — those run only here, in this trusted build
 * step). The generated statements are guard-compatible with the existing
 * communityD1LoadSnapshot RPC (isBootstrapAllowedStatement allows CREATE+INSERT),
 * so the d1_native path can load a full community schema with NO shard-guard
 * widening.
 *
 * Also emits the migration name+checksum list so the d1 path can seed
 * `schema_migrations` (the operator records these; schema-state checks rely on it).
 *
 * Run: `bun run scripts/generate-community-schema-snapshot.ts`
 * (re-run whenever the community-template migrations change).
 */
import { createClient } from "@libsql/client"
import { createHash } from "node:crypto"
import { mkdir, readdir, readFile, writeFile } from "node:fs/promises"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"
import { resolveCoreRepoPath } from "../shared/core-repo-paths"
import { splitSqlStatements, toSqliteCompatibleStatements } from "../shared/sql-migration"

const SCHEMA_MIGRATIONS_DDL = `CREATE TABLE IF NOT EXISTS schema_migrations (
  migration_name TEXT PRIMARY KEY,
  migration_label TEXT NOT NULL,
  checksum TEXT NOT NULL,
  applied_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
)`

const OUT_REL = "../src/lib/communities/provisioning/generated/community-schema-snapshot.ts"

async function main(): Promise<void> {
  const migrationsDir = resolveCoreRepoPath("db/community-template/migrations")
  const files = (await readdir(migrationsDir)).filter((f) => f.endsWith(".sql")).sort()

  const db = createClient({ url: ":memory:" })
  await db.execute(SCHEMA_MIGRATIONS_DDL)

  const migrations: { name: string; checksum: string }[] = []
  for (const file of files) {
    const sql = await readFile(join(migrationsDir, file), "utf8")
    migrations.push({ name: file, checksum: createHash("sha256").update(sql).digest("hex") })
    for (const raw of splitSqlStatements(sql)) {
      for (const stmt of toSqliteCompatibleStatements(raw)) {
        const trimmed = stmt.trim()
        if (!trimmed) continue
        const verb = trimmed.slice(0, 6).toUpperCase()
        if (verb === "BEGIN " || trimmed.toUpperCase() === "COMMIT" || trimmed.toUpperCase() === "BEGIN") continue
        await db.execute(trimmed)
      }
    }
  }

  const rows = (
    await db.execute(
      "SELECT type, name, sql FROM sqlite_master WHERE sql IS NOT NULL " +
        "AND name NOT LIKE 'sqlite_%' AND name NOT LIKE '_cf_%' " +
        "ORDER BY CASE type WHEN 'table' THEN 0 ELSE 1 END, name",
    )
  ).rows
  const statements = rows.map((r) => `${String(r.sql).trim()};`)

  const body =
    `// GENERATED by scripts/generate-community-schema-snapshot.ts — DO NOT EDIT.\n` +
    `// Final-form community-local schema (CREATE-only), produced by replaying the\n` +
    `// ${files.length} core/db/community-template migrations into an in-memory DB and\n` +
    `// dumping sqlite_master. Used by the d1_native provisioning path (§8.7) to load\n` +
    `// a full community schema via communityD1LoadSnapshot with NO bootstrap-guard\n` +
    `// widening (no ALTER/DROP/PRAGMA reach the shard — only these CREATEs do).\n\n` +
    `export const COMMUNITY_SCHEMA_STATEMENTS: readonly string[] = ${JSON.stringify(statements, null, 2)}\n\n` +
    `export const COMMUNITY_SCHEMA_MIGRATIONS: readonly { name: string; checksum: string }[] = ${JSON.stringify(migrations, null, 2)}\n`

  const outPath = join(dirname(fileURLToPath(import.meta.url)), OUT_REL)
  await mkdir(dirname(outPath), { recursive: true })
  await writeFile(outPath, body)
  console.log(`generated: ${statements.length} schema statements, ${migrations.length} migrations from ${files.length} files`)
}

await main()
