export type Env = {
  // Runtime
  BUILD_GIT_REF?: string
  BUILD_GIT_SHA?: string
  BUILD_TIMESTAMP?: string
  ENVIRONMENT?: string
  DEV_MEMORY_STORE_ENABLED?: string
  CONTROL_PLANE_DATABASE_URL?: string
  CORS_ALLOWED_ORIGINS?: string
  MATERIALIZED_PUBLIC_HOME_FEED_LOCALES?: string
  PIRATE_ADMIN_TOKEN?: string
  SENTRY_DSN?: string

  // Analytics
  ANALYTICS_ENABLED?: string
  ANALYTICS_HMAC_SECRET?: string
  TINYBIRD_HOST?: string
  TINYBIRD_INGEST_TOKEN?: string
  TINYBIRD_READ_TOKEN?: string
  TINYBIRD_EVENTS_DATASOURCE?: string

  // Community databases and provisioning
  TURSO_COMMUNITY_DB_WRAP_KEY?: string
  TURSO_COMMUNITY_DB_WRAP_KEY_VERSION?: string
  LOCAL_COMMUNITY_DB_ROOT?: string
  COMMUNITY_PROVISION_OPERATOR_AUTH_TOKEN?: string
  COMMUNITY_PROVISION_EXPECTED_ORGANIZATION_SLUG?: string
  COMMUNITY_PROVISION_DEFAULT_GROUP_LOCATION?: string
  COMMUNITY_PROVISION_ALLOWED_GROUP_LOCATIONS?: string

  // Auth and identity
  JWT_BASED_AUTH_ENABLED?: string
  JWT_BASED_AUTH_SHARED_SECRET?: string
  JWT_BASED_AUTH_ISSUERS?: string
  JWT_BASED_AUTH_AUDIENCE?: string
  AUTH_UPSTREAM_JWT_ISSUER?: string
  AUTH_UPSTREAM_JWT_AUDIENCE?: string
  AUTH_UPSTREAM_JWT_SHARED_SECRET?: string
  PIRATE_APP_JWT_PRIVATE_KEY?: string
  PIRATE_APP_JWT_PUBLIC_KEY?: string
  PIRATE_APP_JWT_ISSUER?: string
  PIRATE_APP_JWT_AUDIENCE?: string
  PIRATE_APP_JWT_TTL_SECONDS?: string
  PIRATE_WEB_PUBLIC_ORIGIN?: string
  OAUTH_DEVICE_CODE_TTL_SECONDS?: string
  OAUTH_DEVICE_POLL_INTERVAL_SECONDS?: string
  OAUTH_DEVICE_REFRESH_TOKEN_TTL_SECONDS?: string
  PRIVY_APP_ID?: string
  PRIVY_APP_SECRET?: string
  PRIVY_API_URL?: string
  PRIVY_JWT_VERIFICATION_KEY?: string
  REDDIT_PROFILE_CHECK_USER_AGENT?: string
  REDDIT_PULLPUSH_BASE_URL?: string
  VERY_API_URL?: string
  VERY_APP_ID?: string
  VERY_NATIVE_OAUTH_ENABLED?: string
  VERY_OAUTH_CLIENT_ID?: string
  VERY_OAUTH_CLIENT_SECRET?: string
  VERY_OAUTH_ISSUER?: string
  VERY_OAUTH_JWKS_URL?: string
  VERY_OAUTH_REDIRECT_URI?: string
  VERY_OAUTH_TOKEN_URL?: string
  VERY_NATIVE_AUTH_CODE_TTL_SECONDS?: string
  VERY_VERIFY_URL?: string
  VERY_TRUST_BRIDGE_COMPLETION_ON_VERIFIER_5XX?: string
  VERY_TRUST_LOCAL_WIDGET_COMPLETION?: string
  VERIFICATION_DEBUG_LOGS?: string
  PLATFORM_APPROVED_KYA_PROVIDERS?: string
  CLAWKEY_API_URL?: string
  SELF_APP_NAME?: string
  SELF_ENDPOINT?: string
  SELF_ENDPOINT_TYPE?: string
  VERY_BRIDGE_API_URL?: string
  PASSPORT_API_URL?: string
  PASSPORT_API_KEY?: string
  PASSPORT_SCORER_ID?: string
  ALTCHA_HMAC_SECRET?: string
  ALTCHA_HMAC_KEY_SECRET?: string
  ALTCHA_POW_COST?: string
  ALTCHA_POW_COUNTER_MIN?: string
  ALTCHA_POW_COUNTER_MAX?: string
  ALTCHA_CHALLENGE_TTL_SECONDS?: string
  ALTCHA_CHALLENGE_RATE_LIMIT?: string
  ALTCHA_CHALLENGE_RATE_LIMIT_WINDOW_SECONDS?: string

  // Media storage
  FILEBASE_S3_ACCESS_KEY?: string
  FILEBASE_S3_SECRET_KEY?: string
  FILEBASE_S3_ENDPOINT?: string
  FILEBASE_S3_REGION?: string
  FILEBASE_MEDIA_BUCKET?: string
  PIRATE_API_PUBLIC_ORIGIN?: string
  IPFS_GATEWAY_URL?: string
  SWARM_BEE_API_URL?: string
  SWARM_POSTAGE_BATCH_ID?: string
  SWARM_FEED_PRIVATE_KEY?: string
  SWARM_FEED_TOPIC_NAMESPACE?: string

  // EVM and commerce
  ETHEREUM_RPC_URL?: string
  COURTYARD_API_URL?: string
  COURTYARD_INVENTORY_CACHE_TTL_MS?: string
  BASE_MAINNET_RPC_URL?: string
  BASE_SEPOLIA_RPC_URL?: string
  PIRATE_CHECKOUT_OPERATOR_ADDRESS?: string
  PIRATE_CHECKOUT_OPERATOR_PRIVATE_KEY?: string
  PIRATE_CHECKOUT_RPC_URL?: string
  PIRATE_CHECKOUT_SOURCE_CHAIN_ID?: string
  PIRATE_CHECKOUT_USDC_TOKEN_ADDRESS?: string
  // Caps RPC receipt waits for routed checkout funding confirmation. Paid
  // handle claims can be retried with the same funding_tx_ref after timeout.
  // Use 15000-30000 for pilot smoke.
  PIRATE_CHECKOUT_TX_WAIT_TIMEOUT_MS?: string

  // Public name rate limiting
  PUBLIC_NAME_QUOTE_RATE_LIMIT_IP?: string
  PUBLIC_NAME_QUOTE_RATE_LIMIT_WALLET?: string
  PUBLIC_NAME_QUOTE_RATE_LIMIT_WINDOW_SECONDS?: string

  // Story and song processing
  STORY_CHAIN_ID?: string
  STORY_RPC_URL?: string
  STORY_RPC_FALLBACK_URLS?: string
  STORY_ROYALTY_SPG_NFT_CONTRACT?: string
  STORY_ROYALTY_COMMERCIAL_REV_SHARE_PCT?: string
  STORY_ROYALTY_DEFAULT_MINTING_FEE_WEI?: string
  STORY_ROYALTY_MAX_LICENSE_TOKENS?: string
  STORY_ROYALTY_POLICY_LAP_ADDRESS?: string
  COMMUNITY_JOB_WORKER_INTERVAL_MS?: string
  COMMUNITY_JOB_WORKER_MAX_JOBS_PER_COMMUNITY?: string
  COMMUNITY_JOB_WORKER_MAX_COMMUNITIES_PER_TICK?: string
  SONG_PREVIEW_FFMPEG_BIN?: string
  SONG_PREVIEW_FFPROBE_BIN?: string
  AGORA_APP_ID?: string
  AGORA_APP_CERTIFICATE?: string
  LIVE_ROOM_AGORA_TOKEN_TTL_SECONDS?: string
  LIVE_ROOM_JACKTRIP_HOST?: string
  LIVE_ROOM_JACKTRIP_HOST_TEMPLATE?: string
  LIVE_ROOM_JACKTRIP_PORT?: string
  LIVE_ROOM_JACKTRIP_BIND_PORT?: string
  LIVE_ROOM_JACKTRIP_QUALITY?: string
  LIVE_ROOM_JACKTRIP_BUFFER_STRATEGY?: string
  LIVE_ROOM_JACKTRIP_LINUX_AUDIO_SETUP_RECOMMENDED?: string
  LIVE_ROOM_RUNTIME?: DurableObjectNamespace
  STORY_TX_WAIT_TIMEOUT_MS?: string
  STORY_RUNTIME_SIGNER_MIN_BALANCE_WEI?: string
  STORY_RUNTIME_SIGNER_TARGET_BALANCE_WEI?: string
  STORY_DIRECT_TX_MAX_FEE_PER_GAS_WEI?: string
  STORY_DIRECT_TX_MAX_PRIORITY_FEE_PER_GAS_WEI?: string
  STORY_DIRECT_TX_GAS_LIMIT_MAX?: string
  STORY_DIRECT_TX_GAS_ESTIMATE_BUFFER_BPS?: string
  STORY_RUNTIME_PRIVATE_KEY?: string
  STORY_OPERATOR_PRIVATE_KEY?: string
  STORY_OPERATOR_PKP_ADDRESS?: string
  STORY_OPERATOR_PKP_PUBLIC_KEY?: string
  STORY_OPERATOR_ACTION_CID_PUBLISH_ASSET_VERSION?: string
  LIT_CHIPOTLE_API_BASE_URL?: string
  LIT_CHIPOTLE_OPERATOR_API_KEY?: string
  STORY_CDR_WRITER_PRIVATE_KEY?: string
  STORY_CDR_WRITER_PKP_ADDRESS?: string
  STORY_CDR_WRITER_PKP_PUBLIC_KEY?: string
  STORY_CDR_WRITER_ACTION_CID_ALLOCATE_WRITE?: string
  LIT_CHIPOTLE_CDR_WRITER_API_KEY?: string
  STORY_ACCESS_CONTROLLER_PRIVATE_KEY?: string
  STORY_ACCESS_CONTROLLER_PKP_ADDRESS?: string
  STORY_ACCESS_CONTROLLER_PKP_PUBLIC_KEY?: string
  STORY_ACCESS_CONTROLLER_ACTION_CID_SIGN_ACCESS_PROOF?: string
  LIT_CHIPOTLE_ACCESS_CONTROLLER_API_KEY?: string
  MUSIC_PURCHASE_STORY_SETTLEMENT_PRIVATE_KEY?: string
  MUSIC_PURCHASE_STORY_SETTLEMENT_PKP_ADDRESS?: string
  MUSIC_PURCHASE_STORY_SETTLEMENT_PKP_ID?: string
  MUSIC_PURCHASE_STORY_SETTLEMENT_PKP_PUBLIC_KEY?: string
  LIT_CHIPOTLE_STORY_SETTLEMENT_API_KEY?: string
  STORY_SETTLEMENT_ACTION_CID_SETTLE?: string
  STORY_SETTLEMENT_ACTION_CID_ROYALTY_SYNC?: string

  // Payouts and funding
  ENDAOMENT_PAYOUT_PRIVATE_KEY?: string
  ENDAOMENT_RPC_URL?: string
  ENDAOMENT_CHAIN_ID?: string
  ENDAOMENT_USDC_TOKEN_ADDRESS?: string
  ENDAOMENT_REGISTRY_ADDRESS?: string
  ENDAOMENT_TX_WAIT_TIMEOUT_MS?: string
  STORY_CONTRACT_OWNER_PRIVATE_KEY?: string
  STORY_RUNTIME_FUNDER_PRIVATE_KEY?: string

  // AI and external analysis
  OPENAI_API_KEY?: string
  OPENAI_MODERATION_BASE_URL?: string
  OPENAI_MODERATION_MODEL?: string
  OPENAI_MODERATION_SEXUAL_MINORS_BLOCK_THRESHOLD?: string
  OPENAI_MODERATION_TIMEOUT_MS?: string
  OPENROUTER_API_KEY?: string
  OPENROUTER_BASE_URL?: string
  OPENROUTER_MODEL?: string
  OPENROUTER_TIMEOUT_MS?: string
  OPENROUTER_VISUAL_POLICY_MODEL?: string
  OPENROUTER_VISUAL_POLICY_TIMEOUT_MS?: string
  OPENROUTER_TRANSLATION_MODEL?: string
  OPENROUTER_TRANSLATION_MAX_COMPLETION_TOKENS?: string
  OPENROUTER_TRANSLATION_TIMEOUT_MS?: string
  OPENROUTER_LINK_SUMMARY_MODEL?: string
  OPENROUTER_LINK_SUMMARY_TIMEOUT_MS?: string
  OPENROUTER_LINK_SUMMARY_TRANSLATION_MODEL?: string
  OPENROUTER_LINK_SUMMARY_TRANSLATION_TIMEOUT_MS?: string
  OPENROUTER_LABELING_MODEL?: string
  OPENROUTER_LABELING_TIMEOUT_MS?: string
  FIRECRAWL_API_KEY?: string
  ELEVENLABS_API_KEY?: string
  ELEVENLABS_FORCE_ALIGNMENT_URL?: string
  ELEVENLABS_TIMEOUT_MS?: string
  ACRCLOUD_ACCESS_KEY?: string
  ACRCLOUD_ACCESS_SECRET?: string
  ACRCLOUD_HOST?: string
  ACRCLOUD_IDENTIFY_PATH?: string
  ACRCLOUD_TIMEOUT_MS?: string
  ACRCLOUD_PERSONAL_ACCESS_TOKEN?: string
  ACRCLOUD_BUCKET_ID?: string
  ACRCLOUD_CONSOLE_BASE_URL?: string

  // Namespace verifiers
  SPACES_VERIFIER_BASE_URL?: string
  SPACES_VERIFIER_AUTH_TOKEN?: string
  SPACES_VERIFIER_CHALLENGE_DOMAIN?: string
  SPACES_CHALLENGE_TTL_HOURS?: string
  HNS_VERIFIER_BASE_URL?: string
  HNS_VERIFIER_AUTH_TOKEN?: string
  HNS_CHALLENGE_TTL_HOURS?: string

  // Service bindings
  COMMUNITY_PROVISION_OPERATOR?: Fetcher
}
